2024-02-09 04:31:04,149 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6f1660>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:04,200 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6f3f70>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:04,223 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6f0dc0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:08,873 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32fee0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:10,773 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32ed40>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:11,850 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddfc27a0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:11,894 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddfc0a60>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:11,912 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6ab7f0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:11,943 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32d450>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
